import "./globals.css";

export const metadata = {
  title: "Shopping List",
  description: "Generated by Jordan Hamdy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}

